version: 2

models:
  - name: stg_ingestion__customers
    description: >
      Cleaned and standardized customer records from the sample system (Silver layer).
      All fields are cast/trimmed via standard macros — no ad-hoc transformations.
    columns:
      - name: id
        description: "Surrogate key for customer"
        data_type: string
        tests:
          - not_null
          - unique
      - name: nk
        description: "Natural key for customer (original customer_id)"
        data_type: string
        tests:
          - not_null
      - name: name
        description: "Customer name"
        data_type: string
      - name: email
        description: "Customer email address"
        data_type: string
        tests:
          - not_null
      - name: _source_file_name
        description: "Source file name from ingestion"
        data_type: string
      - name: _ingestion_id
        description: "Surrogate key for ingestion batch"
        data_type: string
      - name: _ingestion_nk
        description: "Natural key for ingestion batch"
        data_type: string
      - name: _ingested_at_brt
        description: "Timestamp when record was ingested (Brazilian Time)"
        data_type: timestamp
