name: medallion_bq
version: "1.0.0"
config-version: 2

profile: medallion_bq

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analysis"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

require-dbt-version: [">=1.7.0", "<2.0.0"]

models:
  medallion_bq:

    sources:
      +tags: ["sources"]

    staging:
      +schema: "staging"
      +materialized: view
      +tags: ["staging", "bi"]

    analytics:
      +schema: "analytics"
      +materialized: table
      +tags: ["analytics", "bi"]


vars:
  timezone: "UTC"

dispatch: []
