medallion_bq:
  target: "{{ env_var('DBT_TARGET', 'prod') }}"
  outputs:
    prod:
      type: bigquery
      method: "{{ env_var('DBT_BQ_METHOD', 'oauth') }}"
      project: "{{ env_var('DBT_BQ_PROJECT') }}"
      dataset: "{{ env_var('DBT_BQ_DATASET', 'silver_prod') }}"
      location: "{{ env_var('DBT_BQ_LOCATION', 'US') }}"
      keyfile: "{{ env_var('DBT_BQ_KEYFILE', '') }}"
      threads: 4
      priority: interactive
      job_execution_timeout_seconds: 300
      create_schema: false
