version: 2

models:
  - name: stg_ingestion__transactions
    description: >
      Cleaned and standardized transaction records from the sample system (Silver layer).
      Deduplicated to keep only the latest version of each transaction based on transaction date.
      All fields are cast/trimmed via standard macros.
    columns:
      - name: id
        description: "Composite surrogate key for unique transaction record"
        data_type: string
        tests:
          - not_null
          - unique
      - name: transaction_id
        description: "Surrogate key for transaction"
        data_type: string
        tests:
          - not_null
      - name: customer_id
        description: "Surrogate key for customer"
        data_type: string
        tests:
          - not_null
      - name: transaction_nk
        description: "Natural key for transaction (original transaction_id)"
        data_type: string
        tests:
          - not_null
      - name: customer_nk
        description: "Natural key for customer (original customer_id)"
        data_type: string
      - name: status
        description: "Transaction status"
        data_type: string
      - name: transaction_date_brt
        description: "Transaction date in Brazilian Time"
        data_type: timestamp
      - name: _source_file_name
        description: "Source file name from ingestion"
        data_type: string
      - name: _ingestion_id
        description: "Surrogate key for ingestion batch"
        data_type: string
      - name: _ingestion_nk
        description: "Natural key for ingestion batch"
        data_type: string
      - name: _ingested_at_brt
        description: "Timestamp when record was ingested (Brazilian Time)"
        data_type: timestamp

  - name: stg_ingestion__transactions_details
    description: >
      Cleaned and standardized transaction details from the sample system (Silver layer).
      Deduplicated to keep only the latest version of each transaction detail.
      Contains transaction type, quantity, and pricing information.
    columns:
      - name: id
        description: "Surrogate key for transaction detail"
        data_type: string
        tests:
          - not_null
          - unique
      - name: nk
        description: "Natural key for transaction (original transaction_id)"
        data_type: string
        tests:
          - not_null
      - name: type
        description: "Transaction type"
        data_type: string
      - name: quantity
        description: "Transaction quantity"
        data_type: numeric
      - name: price_usd
        description: "Transaction price in USD"
        data_type: numeric
      - name: _source_file_name
        description: "Source file name from ingestion"
        data_type: string
      - name: _ingestion_id
        description: "Surrogate key for ingestion batch"
        data_type: string
      - name: _ingestion_nk
        description: "Natural key for ingestion batch"
        data_type: string
      - name: _ingested_at_brt
        description: "Timestamp when record was ingested (Brazilian Time)"
        data_type: timestamp